using System.Runtime.CompilerServices;
// Properties/AssemblyInfo.cs is no longer generated by default in VS2017/.NETStandard,
// so this file is added manually and called 'AssemblyInformation.cs'
[assembly: InternalsVisibleTo("HashLibTest")]