// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection
open System.Runtime.CompilerServices

[<assembly:AssemblyTitleAttribute("NBitcoin.Miniscript")>]
[<assembly:AssemblyProductAttribute("NBitcoin.Miniscript")>]
[<assembly:AssemblyVersionAttribute("0.1.0")>]
[<assembly:AssemblyFileVersionAttribute("0.1.0")>]
[<assembly:AssemblyInformationalVersionAttribute("0.1.0")>]
[<assembly:AssemblyMetadataAttribute("ReleaseChannel", "release")>]
[<assembly:AssemblyDescriptionAttribute("(De)Compiler for Bitcoin Miniscript")>]
[<assembly: InternalsVisibleTo("NBitcoin.Miniscript.Tests.CSharp")>]
[<assembly: InternalsVisibleTo("NBitcoin.Miniscript.Tests.FSharp")>]

do ()

module internal AssemblyVersionInformation =
    [<Literal>]
    let AssemblyTitle = "NBitcoin.Miniscript"
    
    [<Literal>]
    let AssemblyProduct = "NBitcoin.Miniscript"
    
    [<Literal>]
    let AssemblyVersion = "0.1.0"
    
    [<Literal>]
    let AssemblyFileVersion = "0.1.0"
    
    [<Literal>]
    let AssemblyInformationalVersion = "0.1.0"
    
    [<Literal>]
    let AssemblyMetadata_ReleaseChannel = "release"
