// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection

[<assembly:AssemblyTitleAttribute("NBitcoin.Miniscript.Tests.FSharp")>]
[<assembly:AssemblyProductAttribute("NBitcoin.Miniscript.Tests.FSharp")>]
[<assembly:AssemblyVersionAttribute("0.1.0")>]
[<assembly:AssemblyMetadataAttribute("ReleaseDate", 
                                     "2017-03-17T00:00:00.0000000")>]
[<assembly:AssemblyFileVersionAttribute("0.1.0")>]
[<assembly:AssemblyInformationalVersionAttribute("0.1.0")>]
[<assembly:AssemblyMetadataAttribute("ReleaseChannel", "release")>]
[<assembly:AssemblyMetadataAttribute("GitHash", 
                                     "bb8964b54bee133e9af64d316dc2cfee16df7f72")>]
do ()

module internal AssemblyVersionInformation =
    [<Literal>]
    let AssemblyTitle = "NBitcoin.Miniscript.Tests.FSharp"
    
    [<Literal>]
    let AssemblyProduct = "NBitcoin.Miniscript.Tests.FSharp"
    
    [<Literal>]
    let AssemblyVersion = "0.1.0"
    
    [<Literal>]
    let AssemblyMetadata_ReleaseDate = "2017-03-17T00:00:00.0000000"
    
    [<Literal>]
    let AssemblyFileVersion = "0.1.0"
    
    [<Literal>]
    let AssemblyInformationalVersion = "0.1.0"
    
    [<Literal>]
    let AssemblyMetadata_ReleaseChannel = "release"
    
    [<Literal>]
    let AssemblyMetadata_GitHash = "bb8964b54bee133e9af64d316dc2cfee16df7f72"
