//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: PaymentRequest.proto
namespace NBitcoin.Proto
{
	using payments = NBitcoin.Proto;
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"Output")]
	internal partial class Output : global::ProtoBuf.IExtensible
	{
		public Output()
		{
		}

		private ulong _amount = (ulong)0;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue((ulong)0)]
		public ulong amount
		{
			get
			{
				return _amount;
			}
			set
			{
				_amount = value;
			}
		}
		private byte[] _script;
		[global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"script", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public byte[] script
		{
			get
			{
				return _script;
			}
			set
			{
				_script = value;
			}
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{
			return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
		}
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"PaymentDetails")]
	internal partial class PaymentDetails : global::ProtoBuf.IExtensible
	{
		public PaymentDetails()
		{
		}

		private string _network = @"main";
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"network", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(@"main")]
		public string network
		{
			get
			{
				return _network;
			}
			set
			{
				_network = value;
			}
		}
		private readonly global::System.Collections.Generic.List<payments.Output> _outputs = new global::System.Collections.Generic.List<payments.Output>();
		[global::ProtoBuf.ProtoMember(2, Name = @"outputs", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<payments.Output> outputs
		{
			get
			{
				return _outputs;
			}
		}

		private ulong _time;
		[global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		public ulong time
		{
			get
			{
				return _time;
			}
			set
			{
				_time = value;
			}
		}
		private ulong _expires = default(ulong);
		[global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"expires", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(ulong))]
		public ulong expires
		{
			get
			{
				return _expires;
			}
			set
			{
				_expires = value;
			}
		}
		private string _memo = "";
		[global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"memo", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string memo
		{
			get
			{
				return _memo;
			}
			set
			{
				_memo = value;
			}
		}
		private string _payment_url = "";
		[global::ProtoBuf.ProtoMember(6, IsRequired = false, Name = @"payment_url", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string payment_url
		{
			get
			{
				return _payment_url;
			}
			set
			{
				_payment_url = value;
			}
		}
		private byte[] _merchant_data = null;
		[global::ProtoBuf.ProtoMember(7, IsRequired = false, Name = @"merchant_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(null)]
		public byte[] merchant_data
		{
			get
			{
				return _merchant_data;
			}
			set
			{
				_merchant_data = value;
			}
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{
			return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
		}
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"PaymentRequest")]
	internal partial class PaymentRequest : global::ProtoBuf.IExtensible
	{
		public PaymentRequest()
		{
		}

		private uint _payment_details_version = (uint)1;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"payment_details_version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue((uint)1)]
		public uint payment_details_version
		{
			get
			{
				return _payment_details_version;
			}
			set
			{
				_payment_details_version = value;
			}
		}
		private string _pki_type = @"none";
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"pki_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(@"none")]
		public string pki_type
		{
			get
			{
				return _pki_type;
			}
			set
			{
				_pki_type = value;
			}
		}
		private byte[] _pki_data = null;
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"pki_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(null)]
		public byte[] pki_data
		{
			get
			{
				return _pki_data;
			}
			set
			{
				_pki_data = value;
			}
		}
		private byte[] _serialized_payment_details;
		[global::ProtoBuf.ProtoMember(4, IsRequired = true, Name = @"serialized_payment_details", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public byte[] serialized_payment_details
		{
			get
			{
				return _serialized_payment_details;
			}
			set
			{
				_serialized_payment_details = value;
			}
		}
		private byte[] _signature = null;
		[global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"signature", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(null)]
		public byte[] signature
		{
			get
			{
				return _signature;
			}
			set
			{
				_signature = value;
			}
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{
			return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
		}
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"X509Certificates")]
	internal partial class X509Certificates : global::ProtoBuf.IExtensible
	{
		public X509Certificates()
		{
		}

		private readonly global::System.Collections.Generic.List<byte[]> _certificate = new global::System.Collections.Generic.List<byte[]>();
		[global::ProtoBuf.ProtoMember(1, Name = @"certificate", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<byte[]> certificate
		{
			get
			{
				return _certificate;
			}
		}

		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{
			return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
		}
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"Payment")]
	internal partial class Payment : global::ProtoBuf.IExtensible
	{
		public Payment()
		{
		}

		private byte[] _merchant_data = null;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"merchant_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(null)]
		public byte[] merchant_data
		{
			get
			{
				return _merchant_data;
			}
			set
			{
				_merchant_data = value;
			}
		}
		private readonly global::System.Collections.Generic.List<byte[]> _transactions = new global::System.Collections.Generic.List<byte[]>();
		[global::ProtoBuf.ProtoMember(2, Name = @"transactions", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<byte[]> transactions
		{
			get
			{
				return _transactions;
			}
		}

		private readonly global::System.Collections.Generic.List<payments.Output> _refund_to = new global::System.Collections.Generic.List<payments.Output>();
		[global::ProtoBuf.ProtoMember(3, Name = @"refund_to", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<payments.Output> refund_to
		{
			get
			{
				return _refund_to;
			}
		}

		private string _memo = "";
		[global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"memo", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string memo
		{
			get
			{
				return _memo;
			}
			set
			{
				_memo = value;
			}
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{
			return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
		}
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"PaymentACK")]
	internal partial class PaymentACK : global::ProtoBuf.IExtensible
	{
		public PaymentACK()
		{
		}

		private payments.Payment _payment;
		[global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"payment", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public payments.Payment payment
		{
			get
			{
				return _payment;
			}
			set
			{
				_payment = value;
			}
		}
		private string _memo = "";
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"memo", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string memo
		{
			get
			{
				return _memo;
			}
			set
			{
				_memo = value;
			}
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{
			return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
		}
	}

}