name: CI

on: [push, pull_request, workflow_dispatch]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  net60:
    name: '6.0'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./Build/CI/install-env.sh
        env:
          DOTNET_INSTALL_DIR: /usr/share/dotnet
          ADDITIONAL_RUNTIME: 6.0.36
      - run: ./Build/CI/tests.sh
        env:
          BUILD_ARGS: /p:AdditionalDefineConstants=SECP256K1_VERIFY
          Framework: net6.0
  dotnetcore31:
    name: '3.1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install libssl
        run: |
          wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb
          sudo dpkg -i libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb
      - run: ./Build/CI/install-env.sh
        env:
          DOTNET_INSTALL_DIR: /usr/share/dotnet
          ADDITIONAL_RUNTIME: 3.1.32
      - run: ./Build/CI/tests.sh
        env:
          BUILD_ARGS: /p:AdditionalDefineConstants=SECP256K1_VERIFY
          Framework: netcoreapp3.1
          # to avoid error "Couldn't find a valid ICU package installed on the system."
          DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
  dotnetcore60standard20:
    name: '6.0 with netstandard2.0'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./Build/CI/install-env.sh
        env:
          DOTNET_INSTALL_DIR: /usr/share/dotnet
          ADDITIONAL_RUNTIME: 6.0.36
      - run: ./Build/CI/tests.sh
        env:
          BUILD_ARGS: /p:TargetFrameworkOverride=netstandard2.0
          Framework: net6.0
  dotnetcore60macos:
    name: '6.0 on Mac-OS'
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./Build/CI/install-env.sh
        env:
          ADDITIONAL_RUNTIME: 6.0.36
      - run: ./Build/CI/tests.sh
        env:
          Framework: net6.0
  dotnetcore60winfx:
    name: '6.0 on Windows NetFramework472'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: dotnet clean -c Release ./NBitcoin.Tests/NBitcoin.Tests.csproj && dotnet nuget locals all --clear
      - run: dotnet test -c Release -v n ./NBitcoin.Tests/NBitcoin.Tests.csproj --filter "RestClient=RestClient|RPCClient=RPCClient|Protocol=Protocol|Core=Core|UnitTest=UnitTest|Altcoins=Altcoins|PropertyTest=PropertyTest" -p:ParallelizeTestCollections=false -f net472
